config/routes.rb
Rails.application.routes.draw do
  

  #get 'resource/new'

  #get 'resource/summary'

  # get 'sections/new'

  root                           'splash#index'

  post   'login'      =>    'sessions#create'
  delete 'logout'     =>    'sessions#destroy'
  get    'login'      =>    'sessions#new'
  post   'login'      =>    'sessions#create'


  get      'premio'     =>       'splash#premio'
  get      'convocatoria'     =>       'splash#convocatoria'
  get      'ganadores'  =>       'splash#ganadores'
  get      'registro'   =>       'splash#registro' 

  get      'admin-cummins' =>   'proyects#index'

  #get     'acciones'        =>    'proposals#actions'
  #get     'actividades'     =>    'proposals#activities'
  #get     'metodologias'    =>    'proposals#methodologies'
  #get     'impactos'        =>    'proposals#impacts'
  #get     'recursos'        =>    'proposals#resources'

  # get      'justificacion'    =>    'proyects#justificacion'
  # patch    'justificacion'    =>    'proyects#justificacion_update'
  # put      'justificacion'    =>    'proyects#justificacion_update'


  resources :recipients
  resources :sections
  
  resources :account_activations, only: [:edit]
  resources :users#, only: [:new, :create]
  resources :proyects do 
    member do 
      get :justificacion
      patch :justificacion_update

      get :petition
      patch :petition_update

      get :gobjectives
      patch :gobjectives_update

      get :eobjectives
      patch :eobjectives_update

      get :beneficiarios
      patch :beneficiarios_update

      get :investment
      patch :investment_update

      get :continuity
      patch :continuity_update

      get :assign
      patch :assign_update

      get :file
      patch :file_update

      patch :zipfile_update

      get :accept
      get :reject

      get :close_proyect

      get :review

      get :success
    end
  end

  resources :proposals do
    member do
      get :actions
      patch :actions_update

      get :activities
      patch :activities_update

      get :impacts
      patch :impacts_update

      get :methodologies
      patch :methodologies_update

      get :resources
      patch :resources_update
    end
  end

  resources :resource do
    member do

      get :summary
      get :adminsummary
    end
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert normal alert-danger">
      La forma contiene <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" id="nav">
  <div class="container navbar-left">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
      <span class= "icon-bar"></span> 
      <span class= "icon-bar"></span>
      <span class= "icon-bar"></span>     
    </button>
     <a class="navbar-brand  navbar-collapse" href="/">
      <%#= link_to root_path do %>
        <%= image_tag "logo2.png", id: "logonav", class: "img-responsive" %>
      <%# end %>
    </a>  
    <div class= "collapse navbar-collapse navHeaderCollapse" id="navegacion">
      <ul id="listanav" class="nav navbar-nav navbar-right">
        <li>
          <%= link_to root_path do %>
            Inicio
          <% end %>
        </li>
        <li>
          <%= link_to premio_path do %>
            Premio
          <% end %>
        </li>
        <li>
          <%= link_to ganadores_path do %>
            Ganadores
          <% end %>
        </li>
        <li>
          <%= link_to convocatoria_path do %>
            Convocatoria 2016
          <% end %>
        </li>
        <% if !logged_in? %>
          <li>
            <%= link_to new_user_path do  %> <!-- #link_to new_user_path do -->
              Registra tu proyecto
            <% end %>
          </li>
        <% else %>
          <% if current_user.admin? %>
            <li>
              <a href="/admin-cummins">
                Proyectos
              </a>
            </li>
            <li><a href="/users">Usuarios</a></li>
          <% else  %>
            <% if current_user.volunteer? %>
              <li>
                <a href="/proyects">Proyectos</a>
              </li>
            <% else %>
              <li>
                <%= link_to edit_proyect_path(current_user.proyect) do %>
                  Edita tu proyecto
                <% end %>
              </li>
              <%  if current_user.proyect.accepted == 1%>
                <li>
                  <%= link_to actions_proposal_path(current_user) do  %> 
                    Etapa final
                  <% end %>
                </li>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
        
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li class="active">
                <%= link_to "Cerrar Session", logout_path, method: :delete %>
                
              </li>
            </ul>
          </li>

        <% else %>
          <li>
            <%= link_to "Iniciar Session", login_path %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</div>
<div class="separator"></div>