config/routes.rb
Rails.application.routes.draw do
  

  #get 'resource/new'

  #get 'resource/summary'

  # get 'sections/new'

  root                           'splash#index'

  post   'login'      =>    'sessions#create'
  delete 'logout'     =>    'sessions#destroy'
  get    'login'      =>    'sessions#new'
  post   'login'      =>    'sessions#create'


  get      'premio'     =>       'splash#premio'
  get      'convocatoria'     =>       'splash#convocatoria'
  get      'ganadores'  =>       'splash#ganadores'
  get      'registro'   =>       'splash#registro' 

  get      'admin-cummins' =>   'proyects#index'

  #get     'acciones'        =>    'proposals#actions'
  #get     'actividades'     =>    'proposals#activities'
  #get     'metodologias'    =>    'proposals#methodologies'
  #get     'impactos'        =>    'proposals#impacts'
  #get     'recursos'        =>    'proposals#resources'

  # get      'justificacion'    =>    'proyects#justificacion'
  # patch    'justificacion'    =>    'proyects#justificacion_update'
  # put      'justificacion'    =>    'proyects#justificacion_update'


  resources :recipients
  resources :sections
  
  resources :account_activations, only: [:edit]
  resources :users#, only: [:new, :create]
  resources :proyects do 
    member do 
      get :justificacion
      patch :justificacion_update

      get :petition
      patch :petition_update

      get :gobjectives
      patch :gobjectives_update

      get :eobjectives
      patch :eobjectives_update

      get :beneficiarios
      patch :beneficiarios_update

      get :investment
      patch :investment_update

      get :continuity
      patch :continuity_update

      get :assign
      patch :assign_update

      get :file
      patch :file_update

      patch :zipfile_update

      get :accept
      get :reject

      get :close_proyect

      get :review

      get :success
    end
  end

  resources :proposals do
    member do
      get :actions
      patch :actions_update

      get :activities
      patch :activities_update

      get :impacts
      patch :impacts_update

      get :methodologies
      patch :methodologies_update

      get :resources
      patch :resources_update
    end
  end

  resources :resource do
    member do

      get :summary
      get :adminsummary
    end
  end

end

app/models/recipient.rb
# == Schema Information
#
# Table name: recipients
#
#  id                :integer          not null, primary key
#  proyect_id        :integer          not null
#  ben_part_eventual :integer          default(0)
#  ben_number        :integer
#  ben_age_range     :integer          default(0)
#  ben_age_range2    :integer          default(0)
#  ben_risk          :integer
#  ben_part_regular  :integer          default(0)
#  ben_risk_exp      :string(255)
#  ben_group         :integer
#  updated_at        :datetime         not null
#  created_at        :datetime         not null
#

class Recipient < ActiveRecord::Base
  belongs_to :proyect

  
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :logged_in_user

  def new
    @proyect = current_user.proyect
    @recipient = @proyect.recipients.new
    gon.beneficiarios = @proyect.beneficiarios
  end

  def create
    @recipient = current_user.proyect.recipients.new(recipient_params)
    if @recipient.save
      redirect_to :back
    else
      render 'new'
    end
  end

  def destroy
    current_user.proyect.recipients.find(params[:id]).destroy
    redirect_to new_recipient_path
  end

  private
    def recipient_params
      params.require(:recipient).permit(:ben_group, :ben_age_range, :ben_age_range2, :ben_risk, :ben_risk_exp, :ben_number, :ben_part_regular, :ben_part_eventual)
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/new.html.erb
<%= javascript_include_tag 'recipients' %>


<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h2>3.1 Beneficiarios y Comunidades atendidas</h2>
      <hr>
      <p>
        Completar según se indica a continuación. Se puede agregar el número de grupos de beneficiarios que necesites. <br> <br>
      </p>
      <%= form_for(@recipient) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label :ben_group, "Grupo de beneficiarios" %>
        <%= f.select :ben_group, options_for_select(Proyect::SELECT_BENEF_GROUP.map {|opt| opt}, @recipient.ben_group), {include_blank: false}, {class: "form-control"} %>
        <br>

        <div class="row">
          <div class="col-md-6 pull-left">
            <%= f.label :ben_age_range, "Rango de edad (Desde)" %>
            <%= f.select :ben_age_range, options_for_select((1..100).step(1).to_a.map {|s| ["#{s}", s]}, @recipient.ben_age_range), {include_blank: false}, {class: "form-control"} %>
          </div>
          <div class="col-md-6">
            <%= f.label :ben_age_range2, "Rango de edad (Hasta)" %>
            <%= f.select :ben_age_range2, options_for_select((1..100).step(1).to_a.map {|s| ["#{s}", s]}, @recipient.ben_age_range2), {include_blank: false}, {class: "form-control"} %>
          </div>
        </div>
        <br>
          

        <div class="row">
          <div class="col-md-6 pull-left">
            <%= f.label :ben_risk, "Situación de riesgo / enfermedad" %>
            <%= f.select :ben_risk, options_for_select(Proyect::SELECT_BENEF_RISK.map {|opt| opt}, @recipient.ben_risk), {include_blank: false}, {class: "form-control"} %>
          </div>
          <div class="col-md-6">
            <%= f.label :ben_risk_exp, "¿Cuál?" %>
            <%= f.text_field :ben_risk_exp, class: 'form-control' %>
           </div>
        </div>
        <br>

        <%= f.label :ben_number, "¿Cuántos beneficiarios?" %>
        <%= f.number_field :ben_number, {min: 1, class: 'form-control', required: true} %>
        <br>

        <div class="pull-right">
          <%#= f.submit "Añadir Beneficiario", class: "btn btn-primary" %>
          <button type="submit" class="btn btn-primary"><b>+</b> Añadir beneficiario</button>
        </div>
      <% end %>
      <br>
      <br>

      <h3>Beneficiarios</h3>
      <hr>
      <% @proyect.recipients.each do |recipient| %>
        <% if recipient != @proyect.recipients.last %>
        
          <%= recipient.ben_number %> <%= Proyect::READ_BENEF_GROUP[recipient.ben_group] %> de <%= recipient.ben_age_range %> a <%= recipient.ben_age_range2 %> años.

          <%= Proyect::READ_BENEF_RISK[recipient.ben_risk] %>
          
          <%= link_to "Borrar", recipient, class: "btn btn-danger btn-sm pull-right", method: :delete,
                                      data: {confirm: "¿Seguro que deseas eliminar este grupo de beneficiarios?" } %>

          <hr>
        <%end %>
      <% end %>

      De los <span id="recipients_number_id"><%= @proyect.beneficiarios %></span> beneficiarios:
      <br>
      <br>
      <%= form_for(@proyect, url: beneficiarios_update_proyect_path(@proyect)) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <p>
          ¿Cuántos son eventuales?
        </p>
        <%= f.number_field :ben_part_eventual, {min: 0, max: @proyect.beneficiarios, class: 'form-control', required: true} %>

        <p>
          <br>
          ¿Cuántos son regulares?
        </p>
        <%= f.number_field :ben_part_regular, {min: 0, max: @proyect.beneficiarios, class: 'form-control', required: true} %>
        <br>
        <br>
        

        <div class="alert alert-danger" style="display: none;" id="alerta">
          La suma de los beneficiados eventuales y regulares debe ser igual a <%= @proyect.beneficiarios %>
        </div>  
        

        <%= link_to "Atrás", eobjectives_proyect_path(@proyect), class: "btn btn-default" %>

        <div class="pull-right">
          <%= f.submit "Guardar", class: "btn btn-primary" %>
          <%= link_to "Siguiente", investment_proyect_path(@proyect), class: "btn btn-default" %>
        </div>
      <% end %>
      <br>
      <br>

    </div>
  </div>
</div>