config/routes.rb
Rails.application.routes.draw do
  

  #get 'resource/new'

  #get 'resource/summary'

  # get 'sections/new'

  root                           'splash#index'

  post   'login'      =>    'sessions#create'
  delete 'logout'     =>    'sessions#destroy'
  get    'login'      =>    'sessions#new'
  post   'login'      =>    'sessions#create'


  get      'premio'     =>       'splash#premio'
  get      'convocatoria'     =>       'splash#convocatoria'
  get      'ganadores'  =>       'splash#ganadores'
  get      'registro'   =>       'splash#registro' 

  get      'admin-cummins' =>   'proyects#index'

  #get     'acciones'        =>    'proposals#actions'
  #get     'actividades'     =>    'proposals#activities'
  #get     'metodologias'    =>    'proposals#methodologies'
  #get     'impactos'        =>    'proposals#impacts'
  #get     'recursos'        =>    'proposals#resources'

  # get      'justificacion'    =>    'proyects#justificacion'
  # patch    'justificacion'    =>    'proyects#justificacion_update'
  # put      'justificacion'    =>    'proyects#justificacion_update'


  resources :recipients
  resources :sections
  
  resources :account_activations, only: [:edit]
  resources :users#, only: [:new, :create]
  resources :proyects do 
    member do 
      get :justificacion
      patch :justificacion_update

      get :petition
      patch :petition_update

      get :gobjectives
      patch :gobjectives_update

      get :eobjectives
      patch :eobjectives_update

      get :beneficiarios
      patch :beneficiarios_update

      get :investment
      patch :investment_update

      get :continuity
      patch :continuity_update

      get :assign
      patch :assign_update

      get :file
      patch :file_update

      patch :zipfile_update

      get :accept
      get :reject

      get :close_proyect

      get :review

      get :success
    end
  end

  resources :proposals do
    member do
      get :actions
      patch :actions_update

      get :activities
      patch :activities_update

      get :impacts
      patch :impacts_update

      get :methodologies
      patch :methodologies_update

      get :resources
      patch :resources_update
    end
  end

  resources :resource do
    member do

      get :summary
      get :adminsummary
    end
  end

end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :logged_in_user,   except: [:show]
  before_action :correct_user,   except: [:show, :index, :assign, :assign_update, :file, :file_update, :zipfile_update]
  before_action :editable, except: [:show, :index, :review, :assign, :assign_update, :file, :file_update, :accept, :reject, :zipfile_update]
  before_action :require_admin_session, only: [:index, :show]

  def index
    if current_user.admin?
      @proyects = Proyect.all
    else
      @proyects = Proyect.where(volunteer_id: current_user.id)
    end
    
  end
    
  def show
    @proyect = Proyect.find(params[:id])
    @user = @proyect.user
  end

  def edit
  end  

  def update
    if @proyect.update_attributes(proyect_params)
      if @proyect.is_new?
        redirect_to :back #justificacion_proyect_path(@proyect)
      else
        redirect_to :back # petition_proyect_path(@proyect)  
      end
    else
      render 'edit'
    end
  end

  def justificacion
  end

  def justificacion_update
    if @proyect.update_attributes(justification_params)
      p @proyect.idea_emerge
      redirect_to :back #gobjectives_proyect_path(@proyect)
    else
      render 'justificacion'
    end    
  end

  def accept
    if @proyect.accept
      flash[:success] = "¡Proyecto aceptado!"
    else
      flash[:danger] = "El proyecto ya ha sido evaluado!"
    end
    redirect_to :back
  end

  def reject
    if @proyect.reject
      flash[:success] = "Proyecto rechazado!"
    else
      flash[:danger] = "El proyecto ya ha sido evaluado!"
    end
    redirect_to :back
      
  end

  def file
    @proyect = Proyect.find(params[:id])
  end

  def zipfile_update
    @proyect = Proyect.find(params[:id])
    if @proyect.update_attributes(zipfile_params)
      flash[:success] = "El archivo se subió correctamente"
      redirect_to new_resource_path

    else
      flash[:danger] = "hubo un error!"
      redirect_to new_resource_path
    end
  end

  def file_update
    @proyect = Proyect.find(params[:id])
    if @proyect.update_attributes(file_params)
      redirect_to proyects_path
    else
      render 'file'
    end
  end

  def assign
    @proyect = Proyect.find(params[:id])
  end

  def assign_update
    @proyect = Proyect.find(params[:id])
    if @proyect.update_attributes(assign_params)
      redirect_to proyects_path
    else 
      render 'assign'
    end
  end

  def petition
  end

  def petition_update
    if @proyect.update_attributes(petition_params)
      redirect_to :back #gobjectives_proyect_path(@proyect)
    else
      render 'petition'
    end    
  end

  def gobjectives
  end

  def gobjectives_update
    if @proyect.update_attributes(gobjectives_params)
      redirect_to :back #eobjectives_proyect_path(@proyect)
    else
      render 'gobjectives'
    end
  end

  def eobjectives
  end

  def eobjectives_update
    if @proyect.update_attributes(eobjectives_params)
      redirect_to :back #new_recipient_path # beneficiarios_proyect_path(@proyect)
    else
      render 'gobjectives'
    end
  end

  def beneficiarios_update
    if @proyect.update_attributes(beneficiarios_params)
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def investment
  end

  def investment_update
    if @proyect.update_attributes(investment_params)
      redirect_to :back #continuity_proyect_path(@proyect)
    else
      render 'investment'
    end    
  end

  def continuity
  end

  def continuity_update
    if @proyect.update_attributes(continuity_params)
      redirect_to :back # success_proyect_path(@proyect)
    else
      render 'continuity'
    end
  end

  def success
  end

  def review
  end

  def close_proyect
    @proyect.close
    flash[:success] = "¡Proyecto enviado con éxito!"
    redirect_to :back
    
  end


  private
    def correct_user
      @proyect = Proyect.find(params[:id])
      if !current_user.admin? 
        if current_user.proyect != @proyect 
          redirect_to edit_proyect_path(current_user.proyect)
        end
      end 
    end

    def editable
      unless @proyect.editable?
        flash[:danger] = "El proyecto ha sido enviado. No se puede editar."
        redirect_to review_proyect_path(@proyect)
      end
    end

    def file_params
      params.require(:proyect).permit(:pfile)
    end

    def zipfile_params
      params.require(:proyect).permit(:zipfile)
    end

    def assign_params
      params.require(:proyect).permit(:volunteer_id)
    end

    def proyect_params
      params.require(:proyect).permit(:name, :topic, :existent_new)
    end

    def justification_params
      params.require(:proyect).permit(:idea_emerge, :idea_emerge_a, :idea_emerge_b, :idea_emerge_c, :idea_emerge_exp, :procedure_taken, :importance, :importance_text, :importance_text_b,:importance_text_c,:importance_text_d,:importance_text_e,:importance_text_f,:importance_text_g,:importance_text_h)
    end

    def petition_params
      params.require(:proyect).permit(:improvement_importance_a, :improvement_importance_b, :improvement_importance_c, :improvement_importance_d, :improvement_importance_e, :improvement_importance_f)
    end

    def gobjectives_params
      params.require(:proyect).permit(:col_211_a, :col_211_b, :col_211_c, :col_211_d, :col_211_e, :col_212_a, :col_212_b, :col_212_c, :col_212_d, :col_212_e, :col_212_f)
    end

    def eobjectives_params
      params.require(:proyect).permit(:col_oe1, :col_oe1_a, :col_oe1_b, :col_oe1_c, :col_oe1_d, :col_oe1_e, :col_oe2, :col_oe2_a, :col_oe2_b, :col_oe2_c, :col_oe2_d, :col_oe2_e, :col_oe3, :col_oe3_a, :col_oe3_b, :col_oe3_c, :col_oe3_d, :col_oe3_e)
    end

    def beneficiarios_params
      params.require(:proyect).permit(:ben_part_regular, :ben_part_eventual)
    end

    def investment_params
      params.require(:proyect).permit(:investment_a, :investment_b, :investment_c, :investment_d, :investment_e, :investment_f, :investment_sum, :total_weeks)
    end

    def continuity_params
      params.require(:proyect).permit(:col_continuity_action1, :col_continuity_indicator1, :col_continuity_responsible1, :col_continuity_action2, :col_continuity_indicator2, :col_continuity_responsible2, :col_continuity_action3, :col_continuity_indicator3, :col_continuity_responsible3 )
    end

end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/proyects/assign.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Asignar voluntario</h1>
      <hr>
      <div class="row">
        <div class="col-md-5">
          Nombre de la AC
        </div>
        <div class="col-md-7">
          <%= current_user.ac_name %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Nombre de contacto
        </div>
        <div class="col-md-7">
          <%= current_user.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Cargo de contacto
        </div>
        <div class="col-md-7">
          <%= current_user.charge %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Dirección
        </div>
        <div class="col-md-7">
          <%= current_user.address %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Misión y Visión
        </div>
        <div class="col-md-7">
          <%= current_user.mission_vision %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Años en operación
        </div>
        <div class="col-md-7">
          <%= current_user.yr_operation %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Programas que ofrecen
        </div>
        <div class="col-md-7">
          <%= current_user.programs_offered %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Logros          
        </div>
        <div class="col-md-7">
          <%= current_user.achievements %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Temática a participar
        </div>
        <div class="col-md-7">
          <%= Proyect::READ_TOPIC[@proyect.topic] %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          ¿Es una petición para mejorar un programa ya existente o es un proyecto o programa nuevo?
        </div>
        <div class="col-md-7">
          <%= Proyect::READ_EXISTENT_NEW[@proyect.existent_new] %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          Logros          
        </div>
        <div class="col-md-7">
          <%= current_user.achievements %>
        </div>
      </div>
      <br>
      <br>
      <br>
      <%= form_for(@proyect, url: assign_update_proyect_path) do |f| %>
        <%= f.select(:volunteer_id, User.where(user_type: 2).collect {|p| [ "#{p.name + ' - ' + p.email }", p.id ] }, { include_blank: true }, class: "form-control") %>  
        <br>
        <%= f.submit "Asignar", class: "btn btn-primary" %>
      <% end %>










    </div>
  </div>
</div>

app/views/proyects/beneficiarios.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h2>3.1 Beneficiarios y Comunidades atendidas</h2>
      <hr>
      <%= form_for(@proyect, url: beneficiarios_update_proyect_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label :ben_group, "Grupo de beneficiarios" %>
        <%= f.select :ben_group, options_for_select(Proyect::SELECT_BENEF_GROUP.map {|opt| opt}, @proyect.ben_group), {include_blank: false}, {class: "form-control"}, required: true %>
        <br>

        <div class="row">
          <div class="col-md-6 pull-left">
            <%= f.label :ben_age_range, "Rango de edad (Desde)" %>
            <%= f.select :ben_age_range, options_for_select((1..100).step(1).to_a.map {|s| ["#{s}", s]}, @proyect.ben_age_range), {include_blank: false}, {class: "form-control"} %>
          </div>
          <div class="col-md-6">
            <%= f.label :ben_age_range2, "Rango de edad (Hasta)" %>
            <%= f.select :ben_age_range2, options_for_select((1..100).step(1).to_a.map {|s| ["#{s}", s]}, @proyect.ben_age_range2), {include_blank: false}, {class: "form-control"} %>
          </div>
        </div>
        <br>
          

        <div class="row">
          <div class="col-md-6 pull-left">
            <%= f.label :ben_risk, "Situación de riesgo / enfermedad" %>
            <%= f.select :ben_risk, options_for_select(Proyect::SELECT_BENEF_RISK.map {|opt| opt}, @proyect.ben_risk), {include_blank: false}, {class: "form-control"} %>
          </div>
          <div class="col-md-6">
            <%= f.label :ben_risk_exp, "¿Cuál? (en caso de seleccionar Otra)" %>
            <%= f.text_field :ben_risk_exp, class: 'form-control' %>
           </div>
        </div>
        <br>

        <%= f.label :ben_number, "¿Cuántos beneficiarios?" %>
        <%= f.number_field :ben_number, class: 'form-control' %>
        <br>

        <%= link_to "Atrás", eobjectives_proyect_path(@proyect), class: "btn btn-default" %>
        <%= f.submit "Siguiente", class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/proyects/continuity.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h2>5- Continuidad del Proyecto</h2>
      <h4>
        Mediante qué acciones vas a asegurar que tu programa o proyecto continuará  una vez que se termine este apoyo (Máximo 3)
      </h4>
      <hr>
      <%= form_for(@proyect, url: continuity_update_proyect_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="row">
          <div class="col-md-4">
            <%= f.label :col_continuity_action1, "Acción" %>
            <%= f.text_area :col_continuity_action1, class: 'form-control', required: true %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_indicator1, "Indicador" %>
            <%= f.text_area :col_continuity_indicator1, class: 'form-control', required: true %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_responsible1, "Responsable" %>
            <%= f.text_area :col_continuity_responsible1, class: 'form-control', required: true %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-4">
            <%= f.label :col_continuity_action2, "Acción" %>
            <%= f.text_area :col_continuity_action2, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_indicator2, "Indicador" %>
            <%= f.text_area :col_continuity_indicator2, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_responsible2, "Responsable" %>
            <%= f.text_area :col_continuity_responsible2, class: 'form-control' %>
          </div>
        </div>
        <br>

        <div class="row">
          <div class="col-md-4">
            <%= f.label :col_continuity_action3, "Acción" %>
            <%= f.text_area :col_continuity_action3, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_indicator3, "Indicador" %>
            <%= f.text_area :col_continuity_indicator3, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.label :col_continuity_responsible3, "Responsable" %>
            <%= f.text_area :col_continuity_responsible3, class: 'form-control' %>
          </div>
        </div>

        <br>
        <%= link_to "Atrás", investment_proyect_path(@proyect), class: "btn btn-default" %>
        <div class="pull-right">
          <%= f.submit "Guardar", class: "btn btn-primary" %>
          <%= link_to "Resumen", review_proyect_path(@proyect), class: "btn btn-default" %>
          
        </div>
      <% end %>  
    </div>
  </div>
</div>

app/views/proyects/eobjectives.html.erb
<%= javascript_include_tag 'eobjectives' %>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h3>
        2.2 Objetivo específico:
      </h3>
      <h4>
        ¿Qué distintas actividades vas a poner en práctica para lograr tu objetivo General? <br>
        (Mínimo 1 - Máximo 3 Objetivos)
      </h4>
      <hr>
      <h4>
        <% if !@proyect.is_new? %>
          Tú objetivo general: <%= @proyect.col_211_a %> <br>
          Para mejorar <%= @proyect.col_211_b %> <br>
          Duración: <%= @proyect.col_211_c %> <br>
          <%= @proyect.col_211_d %> <br>
          Midiéndola en: <%= @proyect.col_211_e %>

        <% else %>
          Tú objetivo general: <%= @proyect.col_212_a %>  <br>
          Para cambiar: <%= @proyect.col_212_b %> <br>
          Principal beneficio: <%= @proyect.col_212_c %> <br>
          Para: <%= @proyect.col_212_d %> <br>
          En: <%= @proyect.col_212_e %> <br>
          <%= @proyect.col_212_f %>
        <% end %>

      </h4>
      <%= form_for(@proyect, url: eobjectives_update_proyect_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%#= f.label :col_oe1, "Objetivo Específico 1" %>
        <%#= f.text_field :col_oe1, {maxlength: 100, class: 'form-control', required: true} %>
        <p>Objetivo Específico 1</p>
        <%= f.label :col_oe1_a, "Actividad secundaria o derivada en ar, er, ir" %>
        <%= f.text_field :col_oe1_a, {maxlength: 100, class: 'form-control', required: true} %>
        <%= f.label :col_oe1_b, "¿Cuál es el principal beneficio que vas a lograr?" %>
        <%= f.text_field :col_oe1_b, {maxlength: 100, class: 'form-control', required: true} %>
        <%= f.label :col_oe1_c, "¿Para quienes? Mujeres, niños, edad, discapacitados" %>
        <%= f.text_field :col_oe1_c, {maxlength: 100, class: 'form-control', required: true} %>
        <%= f.label :col_oe1_d, "¿En dónde? Municipio, colonia" %>
        <%= f.text_field :col_oe1_d, {maxlength: 100, class: 'form-control', required: true} %>
        <%= f.label :col_oe1_e, "¿Cómo? A través de capacitación, consultas, equipar, etc." %>
        <%= f.text_field :col_oe1_e, {maxlength: 200, class: 'form-control', required: true} %>
        <br>
        <div id="show_oe1" class="btn btn-default"><b>+</b></div>
        <br>
        <br>

        <%#= f.label :col_oe2, "Objetivo Específico 2" %>
        <%#= f.text_field :col_oe2, {maxlength: 100, class: 'form-control'} %>
        <div id="oe1">
          <p>Objetivo Específico 2</p>
          <%= f.label :col_oe2_a, "Actividad secundaria o derivada en ar, er, ir" %>
          <%= f.text_field :col_oe2_a, {maxlength: 100, class: 'form-control'} %>
          <%= f.label :col_oe2_b, "¿Cuál es el principal beneficio que vas a lograr?" %>
          <%= f.text_field :col_oe2_b, {maxlength: 100, class: 'form-control'} %>
          <%= f.label :col_oe2_c, "¿Para quienes? Mujeres, niños, edad, discapacitados" %>
          <%= f.text_field :col_oe2_c, {maxlength: 100, class: 'form-control'} %>
          <%= f.label :col_oe2_d, "¿En dónde? Municipio, colonia" %>
          <%= f.text_field :col_oe2_d, {maxlength: 100, class: 'form-control'} %>
          <%= f.label :col_oe2_e, "¿Cómo? A través de capacitación, consultas, equipar, etc." %>
          <%= f.text_field :col_oe2_e, {maxlength: 200, class: 'form-control'} %>
          <br>
          <div id="show_oe2" class="btn btn-default"><b>+</b></div>
          <br>
          <br>
        </div>

        <%#= f.label :col_oe3, "Objetivo Específico 3" %>
        <%#= f.text_field :col_oe3, {maxlength: 100, class: 'form-control'} %>
        <div id="oe2">
          <p>Objetivo Específico 3</p>
          <%= f.label :col_oe3_a, "Actividad secundaria o derivada en ar, er, ir" %>
          <%= f.text_field :col_oe3_a, {maxlength: 100, class: 'form-control'} %>
          <%= f.label :col_oe3_b, "¿Cuál es el principal beneficio que vas a lograr?" %>
          <%= f.text_field :col_oe3_b, {maxlength: 100, class: 'form-control'} %>
          <%= f.label :col_oe3_c, "¿Para quienes? Mujeres, niños, edad, discapacitados" %>
          <%= f.text_field :col_oe3_c, {maxlength: 100, class: 'form-control'} %>
          <%= f.label :col_oe3_d, "¿En dónde? Municipio, colonia" %>
          <%= f.text_field :col_oe3_d, {maxlength: 100, class: 'form-control'} %>
          <%= f.label :col_oe3_e, "¿Cómo? A través de capacitación, consultas, equipar, etc." %>
          <%= f.text_field :col_oe3_e, {maxlength: 200, class: 'form-control'} %>
          <br>
        </div>

        <%= link_to "Atrás", gobjectives_proyect_path(@proyect), class: "btn btn-default" %>
        <div class="pull-right">
            <%= f.submit "Guardar", class: "btn btn-primary" %>
            <%= link_to "Siguiente", new_recipient_path, class: "btn btn-default" %>
            
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<br>

app/views/proyects/file.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-12 col-md-offset-3">

      <a href="<%= @proyect.pfile %>"><div class="btn btn-default">Ver archivo</div></a> 
      <br>
      <br>
      <hr>
      <%= form_for(@proyect, url: file_update_proyect_path) do |f| %>
      
        <%= f.file_field :pfile, placeholder: "logo", class: "form-control" %>
        <br>
        <%= f.submit "Subir", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/proyects/gobjectives.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h2>Sección 2- Objetivo general</h2>
      <%= form_for(@proyect, url: gobjectives_update_proyect_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <% if !@proyect.is_new? %>
            <h3>
              2.1.1 FORMATO para redactar el objetivo general DE PETICIÓN
            </h3>
            
            <p>
              Redactar el Objetivo General de la Petición contestando los siguientes puntos:
            </p>

            <%= f.label :col_211_a, "¿Qué estas pidiendo? Descripción de conceptos o actividad principal redactada en ar, er, ir" %>
            <%= f.text_field :col_211_a, {maxlength: 200, class: 'form-control', required: true} %>
            <br>
            <%= f.label :col_211_b, "Para mejorar ¿qué proyecto/ programa o servicio? ¿Qué ofrece este programa o servicio?" %>
            <%= f.text_field :col_211_b, {maxlength: 200, class: 'form-control', required: true} %>
            <br>
            <%= f.label :col_211_c, "¿Cuánto tiempo tienes operando el proyecto/programa u ofreciendo el servicio?" %>
            <%= f.text_field :col_211_c, {maxlength: 50, class: 'form-control', required: true} %>
            <br>
            
            <%= f.label :col_211_d, "¿Cómo vas a mejorar el proyecto/programa o servicio? ¿cuál es la situación actual  y cómo va a ser diferente después de la implementación de esta mejora?" %>
            <%= f.text_field :col_211_d, {maxlength: 200, class: 'form-control', required: true} %>
            <br>
            <%= f.label :col_211_e, "¿Cómo vas a medir esa mejora?, ¿en cuánto tiempo?" %>
            <%= f.text_field :col_211_e, {maxlength: 200, class: 'form-control', required: true} %>
            <br>
            <%= link_to "Atrás", petition_proyect_path(@proyect), class: "btn btn-default" %>

        <!-- 212 -->
        <% else %>
            <h3>
              2.1.2 FORMATO para redactar el objetivo general DE UN PROYECTO O PROGRAMA NUEVO
            </h3>
            <hr>
            <p>
              Redactar el Objetivo General del Proyecto o Programa Nuevo contestando los siguientes puntos: 
            </p>
            <%= f.label :col_212_a, "¿Cuál es la actividad principal que vas a emprender? Actividad principal redactada en ar, er, ir" %>
            <%= f.text_field :col_212_a, {maxlength: 200, class: 'form-control', required: true} %>
            <br>
            <%= f.label :col_212_b, "¿Para cambiar qué situación?" %>
            <%= f.text_field :col_212_b, {maxlength: 200, class: 'form-control', required: true} %>
            <br>
            <%= f.label :col_212_c, "¿Obtener qué beneficio? ¿Cuál es el principal beneficio que vas a lograr?" %>
            <%= f.text_field :col_212_c, {maxlength: 200, class: 'form-control', required: true} %>
            <br>
            <%= f.label :col_212_d, "¿Para quienes? Mujeres, niños, edad, discapacitados" %>
            <%= f.text_field :col_212_d, {maxlength: 50, class: 'form-control', required: true} %>
            <br>
            <%= f.label :col_212_e, "¿En dónde? Municipio, colonia." %>
            <%= f.text_field :col_212_e, {maxlength: 50, class: 'form-control', required: true} %>
            <br>
            <%= f.label :col_212_f, "¿Cómo? A través de capacitación, consultas, equipar, etc." %>
            <%= f.text_field :col_212_f, {maxlength: 50, class: 'form-control', required: true} %>
            <br>
            <%= link_to "Atrás", justificacion_proyect_path(@proyect), class: "btn btn-default" %>
        <% end %>
        <div class="pull-right">
            <%= f.submit "Guardar", class: "btn btn-primary" %>
            <%= link_to "Siguiente", eobjectives_proyect_path(@proyect), class: "btn btn-default" %>

        </div>
      <% end %>

    </div>
  </div>
</div>
<br>
<br>

app/views/proyects/success.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h1 class="text-center">¡Proyecto registrado con éxito!</h1>
      <p>
        Para editar información de tu proyecto, inicia sesión y ve a "Registra tu Proyecto"
      </p>
    </div>
  </div>
</div>