config/routes.rb
Rails.application.routes.draw do
  

  #get 'resource/new'

  #get 'resource/summary'

  # get 'sections/new'

  root                           'splash#index'

  post   'login'      =>    'sessions#create'
  delete 'logout'     =>    'sessions#destroy'
  get    'login'      =>    'sessions#new'
  post   'login'      =>    'sessions#create'


  get      'premio'     =>       'splash#premio'
  get      'convocatoria'     =>       'splash#convocatoria'
  get      'ganadores'  =>       'splash#ganadores'
  get      'registro'   =>       'splash#registro' 

  get      'admin-cummins' =>   'proyects#index'

  #get     'acciones'        =>    'proposals#actions'
  #get     'actividades'     =>    'proposals#activities'
  #get     'metodologias'    =>    'proposals#methodologies'
  #get     'impactos'        =>    'proposals#impacts'
  #get     'recursos'        =>    'proposals#resources'

  # get      'justificacion'    =>    'proyects#justificacion'
  # patch    'justificacion'    =>    'proyects#justificacion_update'
  # put      'justificacion'    =>    'proyects#justificacion_update'


  resources :recipients
  resources :sections
  
  resources :account_activations, only: [:edit]
  resources :users#, only: [:new, :create]
  resources :proyects do 
    member do 
      get :justificacion
      patch :justificacion_update

      get :petition
      patch :petition_update

      get :gobjectives
      patch :gobjectives_update

      get :eobjectives
      patch :eobjectives_update

      get :beneficiarios
      patch :beneficiarios_update

      get :investment
      patch :investment_update

      get :continuity
      patch :continuity_update

      get :assign
      patch :assign_update

      get :file
      patch :file_update

      patch :zipfile_update

      get :accept
      get :reject

      get :close_proyect

      get :review

      get :success
    end
  end

  resources :proposals do
    member do
      get :actions
      patch :actions_update

      get :activities
      patch :activities_update

      get :impacts
      patch :impacts_update

      get :methodologies
      patch :methodologies_update

      get :resources
      patch :resources_update
    end
  end

  resources :resource do
    member do

      get :summary
      get :adminsummary
    end
  end

end

app/models/proposal.rb
# == Schema Information
#
# Table name: proposals
#
#  id                      :integer          not null, primary key
#  action_1a               :string(255)
#  action_1b               :string(255)
#  action_1c               :string(255)
#  action_2a               :string(255)
#  action_2b               :string(255)
#  action_2c               :string(255)
#  action_3a               :string(255)
#  action_3b               :string(255)
#  action_3c               :string(255)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  user_id                 :integer
#  methodology_process     :string(600)
#  methodology_medium      :string(600)
#  methodology_description :string(600)
#  impact_objective1       :string(255)
#  impact_objective2       :string(255)
#  impact_objective3       :string(255)
#  impact_goal1            :string(255)
#  impact_goal2            :string(255)
#  impact_goal3            :string(255)
#  impact_indicator1       :string(255)
#  impact_indicator2       :string(255)
#  impact_indicator3       :string(255)
#  impact_evidence1        :string(255)
#  impact_evidence2        :string(255)
#  impact_evidence3        :string(255)
#

class Proposal < ActiveRecord::Base
	belongs_to :user
	has_one :section
	has_one :resource

	before_create :create_section

	def create_section
    	build_section
    	true
  	end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  def new
    @proposal = Proposal.find_by_user_id(current_user.id)
    if @proposal.nil?
      @proposal = current_user.build_proposal
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def update
    @proposal = current_user.proposal.update_attributes(action_params)
    redirect_to :back
  end

  def actions
    @proyect = current_user.proyect
    @proposal = Proposal.find_by_user_id(current_user.id)
    if @proposal.nil?
      @proposal = current_user.build_proposal
      @proposal.save
    end
  end

  def actions_update
    if @proposal.update_attributes(action_params)
      redirect_to :back #gobjectives_proyect_path(@proyect)
    else
      render 'actions'
    end    
  end

  def activities
  end

  def methodologies
    @proposal = Proposal.find(params[:id])
  end

  def methodologies_update
    @proposal = Proposal.find(params[:id])
    if @proposal.update_attributes(methodologies_params)
      redirect_to :back #gobjectives_proyect_path(@proyect)
    else
      render 'methodologies'
    end
  end

  def impacts
    @proposal = Proposal.find(params[:id])
    proyect = @proposal.user.proyect
    @proposal.impact_objective1 = "#{proyect.col_oe1_a} #{proyect.col_oe1_b} #{proyect.col_oe1_c} #{proyect.col_oe1_d} #{proyect.col_oe1_e}"
    @proposal.impact_objective2 = "#{proyect.col_oe2_a} #{proyect.col_oe2_b} #{proyect.col_oe2_c} #{proyect.col_oe2_d} #{proyect.col_oe2_e}"
    @proposal.impact_objective3 = "#{proyect.col_oe3_a} #{proyect.col_oe3_b} #{proyect.col_oe3_c} #{proyect.col_oe3_d} #{proyect.col_oe3_e}"
      
    end

  def impacts_update
    @proposal = Proposal.find(params[:id])
    if @proposal.update_attributes(impacts_params)
      redirect_to :back #gobjectives_proyect_path(@proyect)
    else
      render 'impacts'
    end
  end

  def resources
  end


  private
  def action_params
      params.require(:proposal).permit(:action_1a, :action_1b, :action_1c, :action_2a, :action_2b, :action_2c, :action_3a, :action_3b, :action_3c)
  end

  def methodologies_params
      params.require(:proposal).permit(:methodology_process, :methodology_medium, :methodology_description)
  end

  def impacts_params
      params.require(:proposal).permit(:impact_objective1, :impact_objective2, :impact_objective3, :impact_goal1, :impact_goal2, :impact_goal3, :impact_indicator1, :impact_indicator2, :impact_indicator3, :impact_evidence1, :impact_evidence2, :impact_evidence3)
  end

end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/actions.html.erb
<%= javascript_include_tag 'continuity' %>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h3>
        Acciones:
      </h3>
      <h4>
        ¿Qué acciones  o resumen de tareas tienes que llevar a cabo para lograrlo? (máximo 3 por objetivo) Resume por tareas afines
      </h4>
      <hr>
      <%= form_for(@proposal) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <p>Objetivo Específico 1</p>
        <%= @proyect.col_oe1_a %>
        para lograr <%= @proyect.col_oe1_b %>
        para <%= @proyect.col_oe1_c %>
        en <%= @proyect.col_oe1_d %>
        <%= @proyect.col_oe1_e %>
        <br>
        

        <%= f.label :action_1a, "Acción 1.1" %>
        <%= f.text_field :action_1a, class: 'form-control', required: true %>
        <br>
        <div id="show_a2a" class="btn btn-default"><b>+</b> Añadir Acción</div>
        
        <div class="row" id="action_2a">
          <div class="col-md-12">
            <%= f.label :action_1b, "Acción 1.2" %>
            <%= f.text_field :action_1b, class: 'form-control' %>
            <br>
            <div id="show_a3a" class="btn btn-default"><b>+</b> Añadir Acción</div>
          </div>
        </div>

        <div class="row" id="action_3a">
          <div class="col-md-12">
            <%= f.label :action_1c, "Acción 1.3" %>
            <%= f.text_field :action_1c, class: 'form-control' %>
            <br>
          </div>
        </div>
        <br>






        <% if @proyect.col_oe2_a != ""%>
          <hr>
          <p>Objetivo Específico 2</p>
          <%= @proyect.col_oe2_a %>
          para lograr <%= @proyect.col_oe2_b %>
          para <%= @proyect.col_oe2_c %>
          en <%= @proyect.col_oe2_d %>
          <%= @proyect.col_oe2_e %>
          <br>
          <%= f.label :action_2a, "Acción 2.1" %>
          <%= f.text_field :action_2a, class: 'form-control' %>
          <br>
          <div id="show_a2b" class="btn btn-default"><b>+</b> Añadir Acción</div>
          <br>
          
          <div class="row" id="action_2b">
            <div class="col-md-12">
              <%= f.label :action_2b, "Acción 2.2" %>
              <%= f.text_field :action_2b, class: 'form-control' %>
              <br>
              <div id="show_a3b" class="btn btn-default"><b>+</b> Añadir Acción</div>
            </div>
          </div>
          <br>
          
          <div class="row" id="action_3b">
            <div class="col-md-12">
              <%= f.label :action_2c, "Acción 2.3" %>
              <%= f.text_field :action_2c, class: 'form-control' %>
            </div>
          </div>
          <br>

        <% end %>
        

        <% if @proyect.col_oe3_a != ""%>
          <hr>
          <p>Objetivo Específico 3</p>
          <%= @proyect.col_oe3_a %>
          para lograr <%= @proyect.col_oe3_b %>
          para <%= @proyect.col_oe3_c %>
          en <%= @proyect.col_oe3_d %>
          <%= @proyect.col_oe3_e %>
          <br>
  


          <%= f.label :action_3a, "Acción 3.1" %>
          <%= f.text_field :action_3a, class: 'form-control' %>
          <br>
          <div id="show_a2c" class="btn btn-default"><b>+</b> Añadir Acción</div>
          <br>

          <div class="row" id="action_2c">
            <div class="col-md-12">
              <%= f.label :action_3b, "Acción 3.2" %>
              <%= f.text_field :action_3b, class: 'form-control' %>
              <br>
              <div id="show_a3c" class="btn btn-default"><b>+</b> Añadir Acción</div>
            </div>
          </div>
          <br>
          
          <div class="row" id="action_3c">
            <div class="col-md-12">
              <%= f.label :action_3c, "Acción 3.3" %>
              <%= f.text_field :action_3c, class: 'form-control' %>
            </div>
          </div>
        <% end %>
          

        <br>

        <div class="pull-right">
            <%= f.submit "Guardar", class: "btn btn-primary" %>
            <%= link_to "Siguiente", new_section_path, class: "btn btn-default" %>
            
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<br>

app/views/proposals/activities.html.erb
<h1>Proposals#activities</h1>
<p>Find me in app/views/proposals/activities.html.erb</p>

app/views/proposals/impacts.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h3>
        Impacto:
      </h3>
      <h4>
        Completa lo que se indica
      </h4>
      <hr>
      <%= form_for(@proposal, url: impacts_update_proposal_path) do |f| %>
      	<table>
      		<thead>
      			<th>Objetivo Especifico</th>
      			<th>Meta</th>
      			<th>Indicador</th>
      			<th>Evidencia</th>
      		</thead>
      		<tbody>
      			<tr>

      				<td><%= f.text_area :impact_objective1, class: 'form-control', :rows => 7%></td>
      				<td><%= f.text_area :impact_goal1, {maxlength: 100, class: 'form-control', required: true, rows: 7} %></td>
      				<td><%= f.text_area :impact_indicator1, {maxlength: 150, class: 'form-control', required: true, rows: 7}%></td>
      				<td><%= f.text_area :impact_evidence1, {maxlength: 255, class: 'form-control', required: true, rows: 7}%></td>
      			</tr>
      			<tr>
      				<td><%= f.text_area :impact_objective2, class: 'form-control', :rows => 7%></td>
      				<td><%= f.text_area :impact_goal2, {maxlength: 100, class: 'form-control', required: true, rows: 7} %></td>
      				<td><%= f.text_area :impact_indicator2, {maxlength: 150, class: 'form-control', required: true, rows: 7}%></td>
      				<td><%= f.text_area :impact_evidence2, {maxlength: 255, class: 'form-control', required: true, rows: 7}%></td>
      			</tr>
      			<tr>
      				<td><%= f.text_area :impact_objective3, class: 'form-control', :rows => 7%></td>
      				<td><%= f.text_area :impact_goal3, {maxlength: 100, class: 'form-control', required: true, rows: 7} %></td>
      				<td><%= f.text_area :impact_indicator3, {maxlength: 150, class: 'form-control', required: true, rows: 7}%></td>
      				<td><%= f.text_area :impact_evidence3, {maxlength: 255, class: 'form-control', required: true, rows: 7}%></td>
      			</tr>
      		</tbody>
      	</table>
      	<br>
      	<div class="pull-right">
            <%= f.submit "Guardar", class: "btn btn-primary" %>
            <%= link_to "Siguiente", new_resource_path, class: "btn btn-default" %>
        </div>
      <% end %>
      <br>
      <br>
      <br>
	</div>
  </div>
</div>

app/views/proposals/methodologies.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-2">
      <h3>
        Metodología:
      </h3>
      <h4>
        Completa lo que se indica
      </h4>
      <hr>
      <%= form_for(@proposal, url: methodologies_update_proposal_path) do |f| %>
      	<table>
      		<thead>
      			<th>Método o procedimiento</th>
      			<th>Medio o Tecnología ¿A través de?</th>
      			<th>¿Cómo se hace?</th>
      		</thead>
      		<tbody>
      			<tr>
      				<td>El método o procedimiento es el proceso o camino sistematico establecido para realizar una tarea o trabajo con el fin de alcanzar un objetivo predeterminado <br>Ejemplo: Capacitación, vacunación, construcción, programa educativo, etc.</td>
      				<td>A través de  (ejemplos): curso o material de la SEMARNAT, Kit de vacunación de la Sria de Salud, Juego interactivo de la SEP, Programa de valores de la UASLP, etc</td>
      				<td>Ejemplos: Sesiones de 2 horas cada semana en formato de clases, un evento cada mes en el centro comunitario, en cada escuela los sábados con la ayuda de los padres de familia, se reparte el material en el mercado, etc.</td>
      			</tr>
      				<td><%= f.text_area :methodology_process, class: 'form-control', :rows => 10%></td>
      				<td><%= f.text_area :methodology_medium, class: 'form-control', :rows => 10%></td>
      				<td><%= f.text_area :methodology_description, class: 'form-control', :rows => 10%></td>
      			<tr>
      			</tr>
      		</tbody>
      	</table>
      	<br>
      	<div class="pull-right">
            <%= f.submit "Guardar", class: "btn btn-primary" %>
            <%= link_to "Siguiente", impacts_proposal_path(@proposal), class: "btn btn-default" %> 
        </div>
      <% end %>
	</div>
  </div>
</div>

app/views/proposals/resources.html.erb
<h1>Aviso:</h1>
<p>"Muchas gracias por llenar el registro, el último formulario estará disponible próximamente"</p>